sonar.projectKey=IgorGuariroba_bfin
sonar.organization=igorguariroba

sonar.sources=src
sonar.tests=tests
sonar.exclusions=dist/**,node_modules/**,drizzle/**
sonar.test.exclusions=tests/**
sonar.test.inclusions=tests/**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov/lcov.info
sonar.sourceEncoding=UTF-8
